# Generated by Django 3.0.5 on 2020-05-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20200505_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_image',
        ),
    ]
