# Generated by Django 3.0.5 on 2020-04-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200423_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_description',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
    ]
