# Generated by Django 3.0.5 on 2020-04-23 06:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_description',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='Description'),
        ),
    ]
