# Generated by Django 3.0.5 on 2020-05-05 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0004_auto_20200427_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Blog User'),
            preserve_default=False,
        ),
    ]
