# Generated by Django 3.0.5 on 2020-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blogs_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
